# Generated by Django 3.0.6 on 2020-10-04 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(verbose_name='Дата создания')),
                ('text', models.CharField(max_length=250, verbose_name='Текст сообщения')),
                ('likes', models.IntegerField(default=0, verbose_name='Количество лайков')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweet', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Твит',
                'verbose_name_plural': 'Твиты',
            },
        ),
    ]
