# Generated by Django 3.0.6 on 2020-10-04 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweeter',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 15, 59, 41, 168877), verbose_name='Дата создания'),
        ),
    ]
