# Generated by Django 3.0.6 on 2020-10-04 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201004_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweeter',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 16, 38, 39, 775757), verbose_name='Дата создания'),
        ),
    ]
