# Generated by Django 3.0.6 on 2020-10-04 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201004_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweeter',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 17, 27, 3, 761980), verbose_name='Дата создания'),
        ),
    ]
